### ISSUE TITLE
Todo for 3.0.0 Rewrite

### ISSUE THREAD

**Issue by DaPigGuy** [DaPigGuy/PiggyAuth#39]
PROJECT DISCONTINUED - if you with to for these to be implemented, please create PR's and add them by yourself.

- [x] Full async
- [x] Sessions
- [x] Session Manager
- [x] Move confirmPassword, confirmedPassword, giveEmail, keepCape, joinMessage, messagetick, timeouttick, tries, wither, & startSession to Session class
- [x] Email Manager
- [x] JSON & YML Support
- [x] SimpleAuth to PiggyAuth
- [x] ServerAuth to PiggyAuth
- [ ] Email Verification
- [ ] Account lock
- [x] Tries for /forgetpassword
- [ ] Xbox Live detection
- [ ] Auto whitelist server if connection to MySQL database is down 
- [ ] LBSG-like sessions.
- [x] Implement PlayerTimeoutEvent (currently unused)
- [x] Auto Updater
- [ ] Add toggle for emails
- [ ] More languages
- [x] Individual player languages
- [ ] More efficient password checking on PlayerChatEvent.
- [ ] More typehints and return types

**Comment by lolmanz0** [comment]
Awesome!

**Comment by Thunder33345** [comment]
should class fy and API fy the email verifier and sender and relateds to provide future compatibility when we add more mail supports
you should also consider using the projects page
https://github.com/MCPEPIG/PiggyAuth/projects

**Comment by MCPEPIG** [comment]
NOTICE: Do not use 3.0.0 as it is currently buggy. I have bug fixes coming.

**Comment by Thunder33345** [comment]
I think something NEEDS to be done on forget password reset using pin
https://github.com/MCPEPIG/PiggyAuth/blob/a7ccdb62ad701df875bb56e2f8eb308545596b8e/src/PiggyAuth/Main.php#L596
someone WILL come along and brute force the pins so i highly recommend you to just allow owner to disable pin completely for the sake of server security

**Comment by MCPEPIG** [comment]
Known bugs:
* Players don't get effects when unregistered or resetpassword
* Register doesn't send pin after unregister

**Comment by DaPigGuy** [comment]
@Thunder33345 I'll add tries like for logging in.

**Comment by lolmanz0** [comment]
I translated new messages.

**Comment by lolmanz0** [comment]
https://www.mediafire.com/download/2k3zkbys98orznb

**Comment by VCraftMCPE** [comment]
you're my fav dev

**Comment by Aericio** [comment]
... it shows deleted comments now wow

**Comment by SalmonDE** [comment]
Addition: More typehints and return types
